server:
  port: 0

spring:
  application:
    name: discovery-client
eureka:
  client:
    register-with-eureka: true # 유레카 서버에 등록하기
    fetch-registry: true # 유레카 서버에서 서버 상태 지속적 감시
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #8761은 유레카 디스커버리 서버 port번호 + /eureka

  # 인스턴스별로 유레카에 보여지는 표기를 다르게 설정함
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


