server:
  port: 8000

spring:
  application:
    name: apigateway-server
#  cloud:
#    gateway:
#      routes:  #?? ??????? ??? routes? ???
#        - id: first-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/first-service/** # /? ????? uri??? ????? ????. => ?? ? : Path=http://localhost:8000/first-service
#
#        - id: second-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second-service/**