server:
  port: 8000

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**

          filters:
#            - AddRequestHeader=fsreqhyml,fsreqhvyml
#            - AddResponseHeader= fsreqhyml,fsreqhvyml
            - CustomFilter  # @Component이 붙어있는 필터 클래스 이름을 작성함


        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            - CustomFilter2
