server:
  port: 0

spring:
  application:
    name: item-service

  # spring.profiles.active:application-[??? ??].yml
  profiles:
    active: pro  #? ? ??? ?????? ??? ??  ??(,)? ???? ?????.

  # MySQL ????
#  datasource:
#    url: ${url}
#    username: ${username_}
#    password: ${password}
#    driver-class-name: ${driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
